### PR TITLE
Add 'shortcuts' module.

### PR DESCRIPTION
**Pull request by ProgVal**
I noticed this code will be duplicated a lot across plugins, so I moved it to libmodule.

### CODE REVIEW

**Comment by Tpt** [comment]
It may be nice to have some tests. The "answer" function name is not very clear.

**Comment by ProgVal** [comment]
any idea for a better name?

**Comment by Tpt** [comment]
build_answer_from_modified_request? But it's a little bit long (but it states exactly what this function does).

**Comment by ProgVal** [comment]
Why not just `build_answer`?
Since it is in a `shortcuts` modules, it's quite obvious that it makes it from other provided data

**Comment by Tpt** [comment]
ok for that

**Comment by ProgVal** [comment]
Done

**Comment by ProgVal** [comment]
Oh, but it's still missing the tests

**Comment by ProgVal** [comment]
Done.

**Pull request merged**
